# Generated by Django 4.2.3 on 2023-07-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sale_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.FloatField(max_length=50),
        ),
    ]
